Repository PD-mini-project/ChattingRoom, pull requests merged in 2023-07, with the labels that each got.

#2 #1 feature: 디렉토리 패키지 구조 셋업
  src/main/java/com/chatting/room/chatmessage/api/ChatMessageController.java
  src/main/java/com/chatting/room/chatmessage/application/ChatMessageService.java
  src/main/java/com/chatting/room/chatmessage/domain/ChatMessage.java
  src/main/java/com/chatting/room/chatmessage/dto/request/chatMessageReq.java
  src/main/java/com/chatting/room/chatmessage/dto/response/ChatMessageResp.java
  src/main/java/com/chatting/room/chatmessage/execption/ChatMessageException.java
  src/main/java/com/chatting/room/chatmessage/repository/ChatMessageRepository.java
  src/main/java/com/chatting/room/chatroom/api/ChatRoomController.java
  src/main/java/com/chatting/room/chatroom/application/ChatRoomService.java
  src/main/java/com/chatting/room/chatroom/domain/ChatRoom.java
  src/main/java/com/chatting/room/chatroom/dto/request/ChatRoomReq.java
  src/main/java/com/chatting/room/chatroom/dto/response/ChatRoomResp.java
  src/main/java/com/chatting/room/chatroom/execption/ChatRoomException.java
  src/main/java/com/chatting/room/chatroom/repository/ChatRoomRepository.java
  src/main/java/com/chatting/room/global/config/JdbcConfig.java
  src/main/java/com/chatting/room/global/error/ControllerAdvice.java
  src/main/java/com/chatting/room/global/error/dto/request/ErrorRequest.java
  src/main/java/com/chatting/room/global/error/dto/response/ErrorResponse.java
  src/main/java/com/chatting/room/global/util/Util.java
  src/main/java/com/chatting/room/user/api/UserController.java
  src/main/java/com/chatting/room/user/application/UserService.java
  src/main/java/com/chatting/room/user/domain/User.java
  src/main/java/com/chatting/room/user/dto/request/UserReq.java
  src/main/java/com/chatting/room/user/dto/response/UserResp.java
  src/main/java/com/chatting/room/user/execption/UserException.java
  src/main/java/com/chatting/room/user/repository/UserRepository.java
Labels: feature

#4 #2 feature: 초기 테이블 스키마 ddl문 추가
  src/main/resources/db/V1_init.sql
Labels: feature

#6 #5 refactor : chatroom으로 테이블 이름 변경
  src/main/resources/db/V1_init.sql
Labels: refactor

#9 #7 #8 feature, refactor: chat 테이블에 colunm 추가, chatmessage 패키지 이름 변경
  build.gradle
  src/main/java/com/chatting/room/chat/api/ChatMessageController.java
  src/main/java/com/chatting/room/chat/application/ChatMessageService.java
  src/main/java/com/chatting/room/chat/domain/ChatMessage.java
  src/main/java/com/chatting/room/chat/dto/request/chatMessageReq.java
  src/main/java/com/chatting/room/chat/dto/response/ChatMessageResp.java
  src/main/java/com/chatting/room/chat/execption/ChatMessageException.java
  src/main/java/com/chatting/room/chat/repository/ChatMessageRepository.java
  src/main/java/com/chatting/room/chatmessage/api/ChatMessageController.java
  src/main/java/com/chatting/room/chatmessage/application/ChatMessageService.java
  src/main/java/com/chatting/room/chatmessage/domain/ChatMessage.java
  src/main/java/com/chatting/room/chatmessage/dto/request/chatMessageReq.java
  src/main/java/com/chatting/room/chatmessage/dto/response/ChatMessageResp.java
  src/main/java/com/chatting/room/chatmessage/execption/ChatMessageException.java
  src/main/java/com/chatting/room/chatmessage/repository/ChatMessageRepository.java
  src/main/resources/application.properties
  src/main/resources/db/V2_add_password_col_to_chatroon.sql
Labels: feature, refactor

#11 #10 feature: chatroom_user 테이블 추가 생성
  src/main/resources/application.properties
  src/main/resources/db/V1_init.sql
  src/main/resources/db/V2_add_password_col_to_chatroom.sql
  src/main/resources/db/V3_add_chatroom_user_table.sql
Labels: feature

#13 #12 feature: RedisConfig 파일 추가
  build.gradle
  src/main/java/com/chatting/room/global/config/JdbcConfig.java
  src/main/java/com/chatting/room/global/config/RedisConfig.java
Labels: feature

#15 #14 feature: User 도메인 생성, Repository 테스트
  src/main/java/com/chatting/room/common/config/RedisConfig.java
  src/main/java/com/chatting/room/common/domain/BaseEntity.java
  src/main/java/com/chatting/room/common/error/ControllerAdvice.java
  src/main/java/com/chatting/room/common/error/dto/request/ErrorRequest.java
  src/main/java/com/chatting/room/common/error/dto/response/ErrorResponse.java
  src/main/java/com/chatting/room/common/util/Util.java
  src/main/java/com/chatting/room/global/error/ControllerAdvice.java
  src/main/java/com/chatting/room/global/error/dto/request/ErrorRequest.java
  src/main/java/com/chatting/room/global/error/dto/response/ErrorResponse.java
  src/main/java/com/chatting/room/global/util/Util.java
  src/main/java/com/chatting/room/user/domain/User.java
  src/main/java/com/chatting/room/user/repository/UserRepository.java
  src/test/java/com/chatting/room/user/repository/UserRepositoryTest.java
Labels: feature

#16 [Feature] User 도메인 생성, Repository 테스트
  src/main/java/com/chatting/room/common/config/RedisConfig.java
  src/main/java/com/chatting/room/common/domain/BaseEntity.java
  src/main/java/com/chatting/room/common/error/ControllerAdvice.java
  src/main/java/com/chatting/room/common/error/dto/request/ErrorRequest.java
  src/main/java/com/chatting/room/common/error/dto/response/ErrorResponse.java
  src/main/java/com/chatting/room/common/util/Util.java
  src/main/java/com/chatting/room/global/error/ControllerAdvice.java
  src/main/java/com/chatting/room/global/error/dto/request/ErrorRequest.java
  src/main/java/com/chatting/room/global/error/dto/response/ErrorResponse.java
  src/main/java/com/chatting/room/global/util/Util.java
  src/main/java/com/chatting/room/user/domain/User.java
  src/main/java/com/chatting/room/user/repository/UserRepository.java
  src/test/java/com/chatting/room/user/repository/UserRepositoryTest.java
Labels: feature

#19 #17 #18 feature: User, Chatroom Entity 생성, User, ChatRoom Repository…
  src/main/java/com/chatting/room/RoomApplication.java
  src/main/java/com/chatting/room/chatroom/domain/ChatRoom.java
  src/main/java/com/chatting/room/chatroom/dto/response/ChatRoomResp.java
  src/main/java/com/chatting/room/chatroom/repository/ChatRoomRepository.java
  src/main/java/com/chatting/room/user/api/UserController.java
  src/main/java/com/chatting/room/user/application/UserService.java
  src/main/java/com/chatting/room/user/domain/User.java
  src/main/java/com/chatting/room/user/dto/response/UserResp.java
  src/main/java/com/chatting/room/user/dto/response/UserRespDto.java
  src/main/resources/application.properties
  src/main/resources/db/V1_init.sql
  src/test/java/com/chatting/room/chatroom/repository/ChatRoomRepositoryTest.java
Labels: feature

#20 #17 #18 feature: User, Chatroom Entity 생성,  User, ChatRoom Repository 생성 및 간단 테스트
  src/main/java/com/chatting/room/RoomApplication.java
  src/main/java/com/chatting/room/chatroom/domain/ChatRoom.java
  src/main/java/com/chatting/room/chatroom/dto/response/ChatRoomResp.java
  src/main/java/com/chatting/room/chatroom/repository/ChatRoomRepository.java
  src/main/java/com/chatting/room/user/api/UserController.java
  src/main/java/com/chatting/room/user/application/UserService.java
  src/main/java/com/chatting/room/user/domain/User.java
  src/main/java/com/chatting/room/user/dto/response/UserResp.java
  src/main/java/com/chatting/room/user/dto/response/UserRespDto.java
  src/main/resources/application.properties
  src/main/resources/db/V1_init.sql
  src/test/java/com/chatting/room/chatroom/repository/ChatRoomRepositoryTest.java
Labels: feature

#23 feature: WebConfig, 글로벌 예외 처리
  build.gradle
  src/main/java/com/chatting/room/chatroom/execption/CategoryNullException.java
  src/main/java/com/chatting/room/chatroom/execption/CategoryNumberException.java
  src/main/java/com/chatting/room/chatroom/execption/CategoryTitleLengthException.java
  src/main/java/com/chatting/room/chatroom/execption/ChatRoomDescriptionLengthException.java
  src/main/java/com/chatting/room/chatroom/execption/ChatRoomException.java
  src/main/java/com/chatting/room/chatroom/execption/ChatRoomNotFoundException.java
  src/main/java/com/chatting/room/chatroom/execption/ChatRoomPasswordException.java
  src/main/java/com/chatting/room/chatroom/execption/ChatRoomPasswordLengthException.java
  src/main/java/com/chatting/room/chatroom/execption/ChatRoomTitleLengthException.java
  src/main/java/com/chatting/room/chatroom/execption/ChatRoomTitleNullException.java
  src/main/java/com/chatting/room/common/config/WebConfig.java
  src/main/java/com/chatting/room/common/error/ControllerAdvice.java
  src/main/java/com/chatting/room/common/error/dto/request/ErrorRequest.java
  src/main/java/com/chatting/room/common/error/dto/response/ErrorResponse.java
  src/main/java/com/chatting/room/common/exception/ApplicationException.java
  src/main/java/com/chatting/room/common/exception/BadRequestException.java
  src/main/java/com/chatting/room/common/exception/ControllerAdvice.java
  src/main/java/com/chatting/room/common/exception/ExceptionType.java
  src/main/java/com/chatting/room/common/exception/NotFoundException.java
  src/main/java/com/chatting/room/common/exception/UnAuthorizedException.java
  src/main/java/com/chatting/room/common/exception/dto/response/ErrorResponse.java
  src/main/java/com/chatting/room/user/api/UserController.java
  src/main/java/com/chatting/room/user/application/UserService.java
  src/main/java/com/chatting/room/user/exception/UserDescriptionLengthException.java
  src/main/java/com/chatting/room/user/exception/UserNameDuplicateException.java
  src/main/java/com/chatting/room/user/exception/UserNameLengthException.java
  src/main/java/com/chatting/room/user/exception/UserNameNullException.java
  src/main/java/com/chatting/room/user/exception/UserNotFoundException.java
  src/main/java/com/chatting/room/user/exception/UserPasswordLengthException.java
  src/main/java/com/chatting/room/user/exception/UserPasswordNullException.java
  src/main/java/com/chatting/room/user/execption/UserException.java
Labels: feature

#24 [Feature] WebConfig 설정, 글로벌 예외 처리로직 추가, 각 예외에 대한 클래스 생성
  build.gradle
  src/main/java/com/chatting/room/chatroom/execption/CategoryNullException.java
  src/main/java/com/chatting/room/chatroom/execption/CategoryNumberException.java
  src/main/java/com/chatting/room/chatroom/execption/CategoryTitleLengthException.java
  src/main/java/com/chatting/room/chatroom/execption/ChatRoomDescriptionLengthException.java
  src/main/java/com/chatting/room/chatroom/execption/ChatRoomException.java
  src/main/java/com/chatting/room/chatroom/execption/ChatRoomNotFoundException.java
  src/main/java/com/chatting/room/chatroom/execption/ChatRoomPasswordException.java
  src/main/java/com/chatting/room/chatroom/execption/ChatRoomPasswordLengthException.java
  src/main/java/com/chatting/room/chatroom/execption/ChatRoomTitleLengthException.java
  src/main/java/com/chatting/room/chatroom/execption/ChatRoomTitleNullException.java
  src/main/java/com/chatting/room/common/config/WebConfig.java
  src/main/java/com/chatting/room/common/error/ControllerAdvice.java
  src/main/java/com/chatting/room/common/error/dto/request/ErrorRequest.java
  src/main/java/com/chatting/room/common/error/dto/response/ErrorResponse.java
  src/main/java/com/chatting/room/common/exception/ApplicationException.java
  src/main/java/com/chatting/room/common/exception/BadRequestException.java
  src/main/java/com/chatting/room/common/exception/ControllerAdvice.java
  src/main/java/com/chatting/room/common/exception/ExceptionType.java
  src/main/java/com/chatting/room/common/exception/NotFoundException.java
  src/main/java/com/chatting/room/common/exception/UnAuthorizedException.java
  src/main/java/com/chatting/room/common/exception/dto/response/ErrorResponse.java
  src/main/java/com/chatting/room/user/api/UserController.java
  src/main/java/com/chatting/room/user/application/UserService.java
  src/main/java/com/chatting/room/user/exception/UserDescriptionLengthException.java
  src/main/java/com/chatting/room/user/exception/UserNameDuplicateException.java
  src/main/java/com/chatting/room/user/exception/UserNameLengthException.java
  src/main/java/com/chatting/room/user/exception/UserNameNullException.java
  src/main/java/com/chatting/room/user/exception/UserNotFoundException.java
  src/main/java/com/chatting/room/user/exception/UserPasswordLengthException.java
  src/main/java/com/chatting/room/user/exception/UserPasswordNullException.java
  src/main/java/com/chatting/room/user/execption/UserException.java
Labels: feature

#35 Feature : 채팅방 view 작업
  build.gradle
  src/main/java/com/chatting/room/chatroom/api/ChatRoomController.java
  src/main/java/com/chatting/room/chatroom/api/ChatroomCategoriesController.java
  src/main/java/com/chatting/room/chatroom/application/ChatRoomService.java
  src/main/java/com/chatting/room/chatroom/application/ChatroomCategoriesService.java
  src/main/java/com/chatting/room/chatroom/domain/Categories.java
  src/main/java/com/chatting/room/chatroom/domain/ChatRoom.java
  src/main/java/com/chatting/room/chatroom/domain/Chatroom_Categories.java
  src/main/java/com/chatting/room/chatroom/dto/request/ChatRoomReq.java
  src/main/java/com/chatting/room/chatroom/dto/response/CategoryRespDto.java
  src/main/java/com/chatting/room/chatroom/dto/response/ChatRoomRespDto.java
  src/main/java/com/chatting/room/chatroom/repository/CategoriesRepository.java
  src/main/java/com/chatting/room/chatroom/repository/ChatRoomRepository.java
  src/main/java/com/chatting/room/chatroom/repository/ChatroomCategoriesRepository.java
  src/main/java/com/chatting/room/user/api/UserController.java
  src/main/java/com/chatting/room/user/application/UserService.java
  src/main/java/com/chatting/room/user/dto/request/UserResetPasswordDto.java
  src/main/resources/application.properties
  src/main/resources/static/css/main.css
  src/main/resources/static/html/chatroom.html
  src/main/resources/static/html/room.html
  src/main/resources/static/index.html
  src/main/resources/static/js/main.js
  src/main/resources/static/js/room.js
  src/main/resources/static/room.ftl
  src/main/resources/templates/loginpage.ftl
  src/main/resources/templates/myPage.ftl
Labels: feature

#36 #34 feature : 채팅방 view 작업
  src/main/java/com/chatting/room/chatroom/api/ChatRoomController.java
  src/main/java/com/chatting/room/chatroom/api/ChatroomCategoriesController.java
  src/main/java/com/chatting/room/chatroom/application/ChatRoomService.java
  src/main/java/com/chatting/room/chatroom/application/ChatroomCategoriesService.java
  src/main/java/com/chatting/room/chatroom/domain/Categories.java
  src/main/java/com/chatting/room/chatroom/domain/ChatRoom.java
  src/main/java/com/chatting/room/chatroom/domain/Chatroom_Categories.java
  src/main/java/com/chatting/room/chatroom/dto/request/ChatRoomReq.java
  src/main/java/com/chatting/room/chatroom/dto/response/CategoryRespDto.java
  src/main/java/com/chatting/room/chatroom/dto/response/ChatRoomRespDto.java
  src/main/java/com/chatting/room/chatroom/repository/CategoriesRepository.java
  src/main/java/com/chatting/room/chatroom/repository/ChatRoomRepository.java
  src/main/java/com/chatting/room/chatroom/repository/ChatroomCategoriesRepository.java
  src/main/resources/application.properties
  src/main/resources/static/css/main.css
  src/main/resources/static/html/chatroom.html
  src/main/resources/static/html/room.html
  src/main/resources/static/index.html
  src/main/resources/static/js/main.js
  src/main/resources/static/js/room.js
  src/main/resources/static/room.ftl
Labels: feature

#39 Dev
  src/main/java/com/chatting/room/user/api/UserController.java
  src/main/java/com/chatting/room/user/application/UserService.java
  src/main/resources/templates/loginpage.ftl
  src/main/resources/templates/myPage.ftl
Labels: feature

#42 [Feature] 채팅리스트, 룸 기능 추가
  src/main/java/com/chatting/room/chatroom/api/ChatRoomController.java
  src/main/resources/static/css/chatlist.css
  src/main/resources/static/css/chatroom.css
  src/main/resources/static/html/ChatList.html
  src/main/resources/static/html/chatroom.html
  src/main/resources/static/js/chatlist.js
  src/main/resources/static/js/chatroom.js
  src/main/resources/static/room.ftl
  src/main/resources/templates/loginpage.ftl
Labels: feature

#43 [Feature] 채팅리스트, 룸 기능 추가
  src/main/java/com/chatting/room/chatroom/api/ChatRoomController.java
  src/main/resources/static/css/chatlist.css
  src/main/resources/static/css/chatroom.css
  src/main/resources/static/html/ChatList.html
  src/main/resources/static/html/chatroom.html
  src/main/resources/static/js/chatlist.js
  src/main/resources/static/js/chatroom.js
  src/main/resources/static/room.ftl
  src/main/resources/templates/loginpage.ftl
Labels: feature

#44 #27, #41 refactor: user, chatroom 패키지 하위 클래스 로직 수정
  build.gradle
  src/main/java/com/chatting/room/RoomApplication.java
  src/main/java/com/chatting/room/chatroom/api/ChatRoomController.java
  src/main/java/com/chatting/room/chatroom/api/ChatroomCategoriesController.java
  src/main/java/com/chatting/room/chatroom/application/ChatRoomService.java
  src/main/java/com/chatting/room/chatroom/application/ChatroomCategoriesService.java
  src/main/java/com/chatting/room/chatroom/domain/Categories.java
  src/main/java/com/chatting/room/chatroom/domain/Category.java
  src/main/java/com/chatting/room/chatroom/domain/ChatRoom.java
  src/main/java/com/chatting/room/chatroom/domain/Chatroom_Category.java
  src/main/java/com/chatting/room/chatroom/dto/request/CreateChatRoomRequest.java
  src/main/java/com/chatting/room/chatroom/dto/response/CategoryRespDto.java
  src/main/java/com/chatting/room/chatroom/dto/response/CategoryResponse.java
  src/main/java/com/chatting/room/chatroom/dto/response/ChatRoomRespDto.java
  src/main/java/com/chatting/room/chatroom/dto/response/ChatRoomResponse.java
  src/main/java/com/chatting/room/chatroom/repository/CategoryRepository.java
  src/main/java/com/chatting/room/chatroom/repository/ChatRoomRepository.java
  src/main/java/com/chatting/room/chatroom/repository/ChatroomCategoriesRepository.java
  src/main/java/com/chatting/room/common/aop/Authentication.java
  src/main/java/com/chatting/room/common/aop/AuthenticationAspect.java
  src/main/java/com/chatting/room/common/aop/LoginUserId.java
  src/main/java/com/chatting/room/common/aop/LoginUserIdResolver.java
  src/main/java/com/chatting/room/common/config/RedisConfig.java
  src/main/java/com/chatting/room/common/exception/ControllerAdvice.java
  src/main/java/com/chatting/room/common/exception/ExceptionType.java
  src/main/java/com/chatting/room/common/redis/RedisSessionService.java
  src/main/java/com/chatting/room/common/util/Patterns.java
  src/main/java/com/chatting/room/common/util/Util.java
  src/main/java/com/chatting/room/user/api/UserController.java
  src/main/java/com/chatting/room/user/application/AuthService.java
  src/main/java/com/chatting/room/user/application/UserService.java
  src/main/java/com/chatting/room/user/domain/User.java
  src/main/java/com/chatting/room/user/dto/request/UserCreateRequest.java
  src/main/java/com/chatting/room/user/dto/request/UserLoginDto.java
  src/main/java/com/chatting/room/user/dto/request/UserLoginRequest.java
  src/main/java/com/chatting/room/user/dto/request/UserReq.java
  src/main/java/com/chatting/room/user/dto/request/UserResetPasswordDto.java
  src/main/java/com/chatting/room/user/dto/request/UserUpdateRequest.java
  src/main/java/com/chatting/room/user/dto/response/UserRespDto.java
  src/main/java/com/chatting/room/user/dto/response/UserResponse.java
  src/main/java/com/chatting/room/user/exception/UserLoginException.java
  src/main/java/com/chatting/room/user/repository/UserRepository.java
  src/main/resources/application.properties
  src/main/resources/db/V1_init.sql
  src/main/resources/db/V2_add_password_col_to_chatroom.sql
Labels: refactor

#45 #27, #41 refactor: user, chatroom 패키지 하위 클래스 로직 수정
  build.gradle
  src/main/java/com/chatting/room/RoomApplication.java
  src/main/java/com/chatting/room/chatroom/api/ChatRoomController.java
  src/main/java/com/chatting/room/chatroom/api/ChatroomCategoriesController.java
  src/main/java/com/chatting/room/chatroom/application/ChatRoomService.java
  src/main/java/com/chatting/room/chatroom/application/ChatroomCategoriesService.java
  src/main/java/com/chatting/room/chatroom/domain/Categories.java
  src/main/java/com/chatting/room/chatroom/domain/Category.java
  src/main/java/com/chatting/room/chatroom/domain/ChatRoom.java
  src/main/java/com/chatting/room/chatroom/domain/Chatroom_Category.java
  src/main/java/com/chatting/room/chatroom/dto/request/CreateChatRoomRequest.java
  src/main/java/com/chatting/room/chatroom/dto/response/CategoryRespDto.java
  src/main/java/com/chatting/room/chatroom/dto/response/CategoryResponse.java
  src/main/java/com/chatting/room/chatroom/dto/response/ChatRoomRespDto.java
  src/main/java/com/chatting/room/chatroom/dto/response/ChatRoomResponse.java
  src/main/java/com/chatting/room/chatroom/repository/CategoryRepository.java
  src/main/java/com/chatting/room/chatroom/repository/ChatRoomRepository.java
  src/main/java/com/chatting/room/chatroom/repository/ChatroomCategoriesRepository.java
  src/main/java/com/chatting/room/common/aop/Authentication.java
  src/main/java/com/chatting/room/common/aop/AuthenticationAspect.java
  src/main/java/com/chatting/room/common/aop/LoginUserId.java
  src/main/java/com/chatting/room/common/aop/LoginUserIdResolver.java
  src/main/java/com/chatting/room/common/config/RedisConfig.java
  src/main/java/com/chatting/room/common/exception/ControllerAdvice.java
  src/main/java/com/chatting/room/common/exception/ExceptionType.java
  src/main/java/com/chatting/room/common/redis/RedisSessionService.java
  src/main/java/com/chatting/room/common/util/Patterns.java
  src/main/java/com/chatting/room/common/util/Util.java
  src/main/java/com/chatting/room/user/api/UserController.java
  src/main/java/com/chatting/room/user/application/AuthService.java
  src/main/java/com/chatting/room/user/application/UserService.java
  src/main/java/com/chatting/room/user/domain/User.java
  src/main/java/com/chatting/room/user/dto/request/UserCreateRequest.java
  src/main/java/com/chatting/room/user/dto/request/UserLoginDto.java
  src/main/java/com/chatting/room/user/dto/request/UserLoginRequest.java
  src/main/java/com/chatting/room/user/dto/request/UserReq.java
  src/main/java/com/chatting/room/user/dto/request/UserResetPasswordDto.java
  src/main/java/com/chatting/room/user/dto/request/UserUpdateRequest.java
  src/main/java/com/chatting/room/user/dto/response/UserRespDto.java
  src/main/java/com/chatting/room/user/dto/response/UserResponse.java
  src/main/java/com/chatting/room/user/exception/UserLoginException.java
  src/main/java/com/chatting/room/user/repository/UserRepository.java
  src/main/resources/application.properties
  src/main/resources/db/V1_init.sql
  src/main/resources/db/V2_add_password_col_to_chatroom.sql
Labels: refactor

#47 #46 feature: @Authentication, @LoginUserId 애노테이션 추가
  src/main/java/com/chatting/room/chatroom/api/ChatRoomController.java
  src/main/java/com/chatting/room/chatroom/repository/ChatRoomRepository.java
  src/main/java/com/chatting/room/common/aop/Authentication.java
  src/main/java/com/chatting/room/common/aop/AuthenticationAspect.java
  src/main/java/com/chatting/room/user/api/UserController.java
  src/main/java/com/chatting/room/user/application/AuthService.java
Labels: feature

#48 #46 feature: @Authentication, @LoginUserId 애노테이션 추가
  src/main/java/com/chatting/room/chatroom/api/ChatRoomController.java
  src/main/java/com/chatting/room/chatroom/repository/ChatRoomRepository.java
  src/main/java/com/chatting/room/common/aop/Authentication.java
  src/main/java/com/chatting/room/common/aop/AuthenticationAspect.java
  src/main/java/com/chatting/room/user/api/UserController.java
  src/main/java/com/chatting/room/user/application/AuthService.java
Labels: feature
